---
title: "Opioids vs. Non-Opioids: A Sleep Study"
---

During my internship with Professor Matheson of the Statistics Department at Amherst College, I spent time comparing the effectiveness of opioids and non-opioids (Tylenol, Ibuprofen, Advil, etc.) among patients who recently had wisdom teeth surgery. Patients were given an ActiGraph that measured their periods of sleep after their surgery for 72 hours and an electric pill bottle that recorded when the bottle was opened and how many pills were removed from the bottle. The sleep data was reviewed by a board-certified sleep physician.

What my professor noticed is that some patients had little blips in their actigraphy records in the middle of the night. The sleep physician originally dismissed these recordings as the patient simply tossing and turning, not in a fully awake state. However, if we lined up the time stamps on the pill bottles to the actigraphy data, we saw that those little blips were the patients getting up in the middle of the night to take more pills. The question was, were the patients waking up in the night to take more pills prescribed opioids or non-opioids? It was my task to provide evidence that the opioid patients were exhibiting worse sleep, more pain, and taking more pills than non-opioid patients, suggesting that non-opioid medication is not inferior to opioid medication.

I spent a great deal of time developing a graphic called a lasagna plot. This specific plot can be used to layer time course data for multiple observations. Below, you can see the code used to read the data, clean and join it together, and then arrange it into the lasagna plot. I interned with Professor Matheson before I had taken any data science courses, so this was one of the first major projects I worked on. Overall, the experience was incredibly rewarding and educational. I got to learn the basics of SAS, but the bulk of my work was in R. Additionally, I was using data from the pilot study, which only had 41 participants. Currently, there are over 1,800 participants.

The black lines represent a pill bottle being opened. What you can see is that patients prescribed opioids were waking up in the night more often and taking more pills than non-opioid patients. With the help of Professor Matheson, this graphic was able to better inform the study's conclusions.

## Lasagna Plot 

<embed src="Lasagna-plot.pdf" width="100%" height="800px">
